server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #############################新增网关配置###########################
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
             # 这个时间后才能起效
            #- After=2021-05-24T16:12:48.509+08:00[Asia/Shanghai]
            #cookie 中username=yang
            #- Cookie=username,yang
            #- Header=X-Request-Id, \d+ #请求头中request-Id为正整数
          filters:
            #过滤器 设置所有的 方法都会自动添加foo=bar
            #- AddRequestParameter=key, bar
            #当请求路径匹配到/hello/world/HiController/**会将包含hello和后边的字符串接去掉转发，
            #StripPrefix=2就代表截取路径的个数，这样配置后当请求/hello/world/HiController/aaa后端匹配到的请求路径，
            #就会变成http://localhost:8762/HiController/aaa
            #- StripPrefix=2
####################################################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka